* Organização e arquitetura de computadores
** Referencias
- Piratas do vale do silicio(Filme)
- Von Neumann(artigo)


* Aulas
** 12/08/22
- Ferramentas:
  - EMU086 -> Simulador de um processador 8086 (primeiro 32bits 86x lançado)

- Assembly passa pelo assembler
- Sistemas Computacionais -> Consiste num conjunto de dispoisitovs eletronicos capazes de processar informações de acordo com o software
  - Memoria
  - Processador
    - Registradores
    - Unidade de controle
    - Unidade de execução
    - ALU -> Processamento de aritmimetica e calculos
  - E/S -> Entrada e Saida
- A Velocidade do processador muda com a quantidade de clock, os Hz
- O 64 bits fez com que fosse possivel armazenar mais numeros para calculos, não ficou mais rapido, ficou mais preciso
*** Perguntas
**** Qual diferença entre organização e arquitetura do computador?
- Arquitetura: se refere a atributos que tem impactos diretos sobre execução logica de um programa ->
    O arquiteto tem que ter o objetivo e oque precisa fazer
- Organização: Unidade operacionais e suas interconexões ->
    Tem que saber como fazer e qual melhor caminho, a implementação.
- Se a arquitetura for igual, a organização poderá ser diferente para atingir os mesmos objetivos, porem com velocidades e processos diferentes
- A arquitetura define o quanto de ram um computador pode ter
- Manter a arquitetura igual faz com que os softwares se mantenham utilizaveis, pois todos foram feitos na mesma arquitetura, preserva e facilita mudanças
**** Quais são as quatro funções do computador?
- Armazenar dados
- Processar dados
- Movimentar dados
- Controle
**** Quais são os principais coomponentes do computador?
- Processador
- Barramento
  - CHIPSET
- Memoria
- I/O(Entrada - Saida)
**** Quais são os principais componentes estruturais do processador?
- Barramento Interno -> Oferece comunicação externa
- Registrados -> Memoria interna
- ALU -> Unidade logica e aritmetica
- Controle -> Controla as operações
*** Resumo
Todos esses tópicos estão ligados, cada um faz uma função em cada nivel de abstração
** 19/08/22
- ALU: Unidade de logica e aritmimetica
- Arquitetura -> oq precisa fazer, quais funções, regra
- Organização -> Como fazer, a logica, como executar, forma
- A organização pode diminuir a velocidade, AMD fez isso paa baratear, porem ficou mais lendo
- Caso algo não tenha na arquitetura passa a ser responsabilidade do programador/organização
- Arquitetura influencia diretamente na execução logica
- O principal motivo da troca do 32x para o 64x foi a necessidade de mais memoria RAM
*** Historia
- ENIAC primeiro computador criado em 1946, programado por interruptores e cabos
- Assembly -> primeira linguagem
-
